--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/AmongUs
build-by-default: true
branches:
  - master
  - hydrogames-dev
projects:
  AmongUs:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: master
        version: ^4.0.1
      - src: PresentKim/arrayutils/arrayutils
        branch: main
        version: ^4.1.0
      - src: PresentKim/png-converter/png-converter
        branch: main
        version: ^1.0.2
...
