#      _                                _   _     
#     / \   _ __ ___   ___  _ __   __ _| | | |___ 
#    / _ \ | '_ ` _ \ / _ \| '_ \ / _` | | | / __|
#   / ___ \| | | | | | (_) | | | | (_| | |_| \__ \
#  /_/   \_\_| |_| |_|\___/|_| |_|\__, |\___/|___/
#                                 |___/
#
# Here you can Customize the AmongUs Plugin Game settings.

# How many games can be made on the server.
# Recommended: 4-8
max_games: 4

# Select which world should the game be made.
world_name: amongus

# Select which world should be the waiting lobby.
waiting_lobby: world